### ISSUE TITLE
Transfer Network traffic by amount of money the app makes

### ISSUE THREAD

**Issue by Besix2** [MRColorR/money4band#28]
The script has a inbuilt solution that the apps get different amounts of the internet speed by how much they make.

**Comment by MRColorR** [comment]
> The script has a inbuilt solution that the apps get different amounts of the internet speed by how much they make.

Could you please elaborate more? I didn't quite understand the sentence, sorry. 
Is this a question? or are you requesting to add such a feature? or did you find something similar in the project code? In the latter case please tell me in which file and on which line you found this problem as I am firmly convinced that in the code of this open source project written by me there is no sort of limiter or traffic amount manager and if so I would just check possible.

**Comment by Besix2** [comment]
For example I have 100mbits internet speed. Bitping makes 1 dollar per gb of internet but honeygain makes 2 dollar per gb. As of now I give bitping 50mb and honeygain 50mb. What I suggest is a way that I can give honeygain 75mb and bitping 25mb because it would boost my profits.

**Comment by MRColorR** [comment]
ok, now I get it. 

The traffic flow is not constant but they are small intermittent data streams and each app has its own traffic. keep in mind that we cannot redirect traffic from one app to another because this one would not accept it or even if it were, it would not pay for it.
If more peole is interested in this functionality, I'll think about introducing a bandwidth manager to give one app more percentage of the bandwidth than another but , again, this would only make sense in circumstances where the total available bandwidth given by the ISP or interface is so limited that it does not allow all and apps to run at full speed at the same time. like 56kbps from the '90s . 

if you want to know more about how these apps work and how they decide how much traffic to forward, search the FAQs on the wiki or even better, for more details, search the individual app sites.

**Comment by Besix2** [comment]
I only asked it because some apps semm to have really low speed. I have a 500mb connection going into the pi but bitping recives like 3mb from the hole bandwith and im asking myself where goes the rest.

**Comment by MRColorR** [comment]
I understand, these apps consume little because they are designed to always work also 24/7 without creating bandwidth problems. There is no way for us to request more traffic than what's offered, even though we know we have plenty of bandwidth.

However, you can add other apps that have been excluded from this project precisely because they require much more bandwidth. For example you could run a mysterium vpn node in docker (this only pays in myst tokens of the polygon blockchain) but be careful to choose which traffic to open your node).
