### ISSUE TITLE
Add Proxy Support

### ISSUE THREAD

**Issue by TatsP** [MRColorR/money4band#30]
Please add Proxy Support for the docker container so that we can run multiple docker containers with different proxies to earn more from one PC.

**Comment by MRColorR** [comment]
This function is already built in. Please, read the readme and the Wiki for more details.

**Comment by TatsP** [comment]
> This function is already built in. Please, read the readme and the Wiki for more details.

The built in functionality does not work, it just passes an optional proxy variable to the docker container which is not used.

**Comment by MRColorR** [comment]
Did you used the script to setup the env file ?

**Comment by TatsP** [comment]
> Did you use the script to setup the env file ?

I have done everything, been trying since almost 2 days. The proxy env variables are used only if the container wants it. I am attaching a link below which might act as a solution to the proxy issue.
https://stackoverflow.com/questions/70971310/how-to-make-docker-container-connect-everything-through-proxy

**Comment by MRColorR** [comment]
Thanks for the link and for your interest in the project, i really appreciate it. 
I already know redsocks and had already tried this route but some apps refused to earn after setting it up,there is still something to check carefully so as fall back the standard env variables for proxy has been used atm. 

The rework of this and other functions of the project scripts is already in the to do list butI'm quite busy at the moment
I can rework this feature and the others, only after my cloud certification exam and after the final discussion of my second degree. I invite you and all others interested to fork the project and to try to code this feature yourself, then do a pull request so that the entire user community can benefit from it. 

The solution mentioned in the link creates a dedicated image and container for this function, it shouldn't be difficult to adapt it, the type of network connector must also be changed to redirect traffic to this container. in terms of performance there shouldn't be too many problems. Perhaps there may even be a ready-made version of it in dockerhub? it would be much easier to add and distribute it with the project.
 
Also keep in mind to use the proxy as mentioned in the wiki you need private proxies because some apps don't allow the use of proxies (see their TOS) and it's not that hard to recognize them.

**Comment by jokinvipo** [comment]
Hello @MRColorR,

Thank you for creating this project.

Its possible to help me using network proxies with this project?

Thank you

**Comment by MRColorR** [comment]
Yes, it is possible, but the proxy configuration needs a rework to handle all apps since some of them ignore the proxy flag. I will work on it after the discussion of my final thesis for my degree in Data Science.

**Comment by engageub** [comment]
Hi All,
To use multiproxy with multiple accounts you may have a look at this.
https://github.com/engageub/InternetIncome

Thank you

**Comment by MRColorR** [comment]
A comment was removed as it is rude to advertise within an issue. Instead any help and good information are really appreciated. Thank you

**Comment by engageub** [comment]
This is not an advertisement instead a working solution to those who are in need of using residential proxies. I have been following this repository for long time and have used your code. But I need to use residential proxies, so I came up with my own script instead of waiting for update for long time. 
The code is transparent and for anyone who needs it for immediate use, can use the script to run the containers while this issue is being resolved and updated. 
This is a community where people share knowledge and help each other.
I have searched open issues with similar problems where people needed help and updated the links.
It's always difficult if you don't know or don't understand. I just updated the open issues to save time for the community and developers. 

Thank you

**Comment by MRColorR** [comment]
This is a good explanation, thank you for writing this instead of a single line with a link, i really appreciate this. 
If you want to help the project feel free to open a pull request. 

At the moment money4band is undergoing a complete rework to make it simpler to use and to accomodate several new functions.

**Comment by engageub** [comment]
Thank you for the response. Not everyone lines to read lengthy comments. So I gave a link mentioning that this satisfies the use case for they have been looking for.  
Thank you

**Comment by MRColorR** [comment]
A new pre-release has been published with the new proxy configuration. Also Money4band is now faster and requires less resources 👍 
You can download the pre-release beta at https://github.com/MRColorR/money4band/releases. 
This issue will be closed but feel free to join the discussion for feedback #40 

Thank you for your support and using money4band 🙂🎉
