### ISSUE TITLE
New proxyrack env parameter

### ISSUE THREAD

**Issue by dorel14** [MRColorR/money4band#64]
**Describe the bug**

Proxyrack not working , i download thé New container and it Ask me for an uid environnement parameter 

**Device (please complete the following information):**
 - Type:  Raspberry Pi 3 B+
 - OS details: [e.g. Linux debian 
 - Platform: [e.g.   / arm64 (64bit) ]
 - Version Stretch 
 
 **Docker**
 - Docker Compose version: 2.20.2
 - Docker version: 24.0.5

**To Reproduce**
1. Docker stop proxyrack 
2. Docker rm proxyrack 
3. Restart apps via runme.sh

**Expected behavior**
Need a New Docker composé and .env parameter 

**Screenshots**

**Additional context**

**Comment by MRColorR** [comment]
Thank you for pointing this out,  I'll look into this during the next week. It should be a straightforward edit.
Are you testing the new pre-release or are you on the last stable release?

**Comment by MRColorR** [comment]
UPDATE: I saw the new variable needed in proxyrack docs,i think this will force users to manually register each new device on the proxyrack web dashboard (minimum 10 characters device id) and then set the variable in the script. As a better approach I could try to create a custom script to add the new devices automatically using a web API request and using the same variable already in use. we'll see

**Comment by dorel14** [comment]
I am on stable release

**Comment by MRColorR** [comment]
A fix for this issue has been pushed to the extra-app branch, feel free to test the new code. 
For now we have focused on making the proxyrack setup simple again, we have automated the creation of uuids as already done for earnapp, the user only has to add the device from the dashboard after starting the stack. in another moment we will think about how to use APIs to fully automate this step again. (Frankly, I don't know why proxyrack's devs decided to un-automate this registration phase since their app already took care of these steps internally in the past).
Also, if all goes well, a new stable version of money4band will be released within a couple of days.
