### ISSUE TITLE
speedyshare - earnfm -pocketstream - iproyal - bitping | Device is not visible

### ISSUE THREAD

**Issue by ModernOTS** [MRColorR/money4band#80]
Hello, I installed money4band on VPS, created special instances for this purpose, installed this script there and used ./runme.sh to configure everything. 
repocket -  works
proxylite - works
bitping - device not visible
honeygain  - works
IPROYAL - device not visible
pocketstream - device not visible
earnfm - device not visible
speedyshare - device not visible

and here's the question why some websites don't work
for example, speedyshare has a very simple configuration, only an auth code is required, yet it does not work. most of the configuration of these sites is limited to email and password, so it should work.
web dashboard don't work http://localhost:8081

**Device (please complete the following information):**
 - Type: [e.g./ Server / 
 - OS details: [e.g. Linux Ubuntu  
 - Platform:  x86_64 ]
 - Version [e.g. Ubuntu 22. lts
 
 **Docker**
 - Docker Compose version: Docker Compose version v2.24.5
 - Docker version: Docker version 25.0.3, build 4debf41

**Comment by ModernOTS** [comment]
Update: I created a new instance on this one with the same parameters and bitping sees the device. the rest remained unchanged

**Comment by MRColorR** [comment]
hello :) Thank you for reporting the issues you've encountered on your VPS. 

- Service Compatibility: Please ensure that you comply with the Terms of Service (ToS) for each application. Not all services permit the use of non-residential IPs, and while some allow server and cloud IPs, others may permit proxies. It's crucial to confirm that your setup aligns with the service requirements.

- check containers logs and see if they report any error

- Local Dashboard Access: Since the service is running on a remote server, the dashboard at http://localhost:8081 will not be accessible directly from your local machine. You can try using SSH port forwarding with a command like `ssh -L 8081:localhost:8081 your_vps_user@your_vps_ip`. This could allow you to access the dashboard through your local browser.

- Firewall and Port Configuration: Check the server provider's firewall and port settings. It's possible that certain ports are blocked or that specific firewall rules are preventing connections to the services. Ensure that the necessary ports are open and that there are no rules that could be blocking these connections.

If you continue to face issues, please provide more detailed logs or error messages, which could help in diagnosing the problem more effectively. you can start money4band in debug mode using the `-d` flag 
If you need more real-time assistance or wish to discuss your issues with other community members, I highly recommend joining our Discord server. Within the community, you can share your experiences, ask for advice, and get tips from other users who might have faced similar issues.
